# Generated by Django 4.1.5 on 2023-01-21 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('status_paid', models.CharField(choices=[('accept', 'Принято'), ('reject', 'Отказ'), ('unknown', 'Неизвестный')], default='unknown', max_length=15)),
                ('category', models.CharField(choices=[('category_1', 'Категория 1'), ('category_2', 'Категория 2'), ('category_3', 'Категория 3')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teasers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
