# Generated by Django 4.1.5 on 2023-01-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='category',
            field=models.CharField(choices=[('CATEGORY_1', 'Категория 1'), ('CATEGORY_2', 'Категория 2'), ('CATEGORY_3', 'Категория 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='status_paid',
            field=models.CharField(choices=[('ACCEPT', 'Принято'), ('REJECT', 'Отказ'), ('UNKNOWN', 'Неизвестный')], default='UNKNOWN', max_length=15),
        ),
    ]
